#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/sinusbot

# fetch installer
if [ ! -e /config/sinusbot ]; then
wget -O /config/sinusbot/sinusbot-beta.tar.bz2 https://www.sinusbot.com/dl/sinusbot-beta.tar.bz2
tar -xjf /config/sinusbot/sinusbot-beta.tar.bz2 -C /config/sinusbot
cp /config/sinusbot/plugin/libsoundbot_plugin.so /etc/TeamSpeak3-Client-linux_amd64/plugins
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /config/sinusbot/youtube-dl
useradd sinusbot
fi

# copy default config
if [ ! -e /config/sinusbot/config.ini.dist ]; then
cp /defaults/config.ini /config/sinusbot/config.ini
fi

# permissions
chown sinusbot:sinusbot -R /config
chmod a+rx /config/sinusbot/youtube-dl
